DROP TABLE IF EXISTS rangley.te_version_features;
DROP TABLE IF EXISTS rangley.td_participant_status;
DROP TABLE IF EXISTS rangley.td_meet_status;
DROP TABLE IF EXISTS rangley.td_features;
DROP TABLE IF EXISTS rangley.td_meet_category;
DROP TABLE IF EXISTS rangley.td_sub_category;
DROP TABLE IF EXISTS rangley.td_notification_type;
DROP TABLE IF EXISTS rangley.td_meet_icon;
DROP TABLE IF EXISTS rangley.tb_meet_participants;
DROP TABLE IF EXISTS rangley.tb_user_inboxes;
DROP TABLE IF EXISTS rangley.tb_notifications;
DROP TABLE IF EXISTS rangley.tb_users;
DROP TABLE IF EXISTS rangley.tb_meet_ids;
DROP TABLE IF EXISTS rangley.tb_change_stamps;
DROP TABLE IF EXISTS rangley.tb_meet_coordinates;
DROP TABLE IF EXISTS rangley.tb_meets;


-- Enable UUIDs if not already
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===== LOOKUP / ENUM / DICTIONARY TABLES =====

CREATE TABLE rangley.te_version_features
(
     version     INT4 NOT NULL
    ,feature_id  INT4 NOT NULL
    
    ,PRIMARY KEY (version, feature_id)
);



CREATE TABLE rangley.td_features
(
     feature_id  INT4		  PRIMARY KEY
    ,name        VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_participant_status
(
     participant_status_id  INT2	     	PRIMARY KEY
    ,name                   VARCHAR(50)  	NOT NULL UNIQUE DEFAULT ''
    ,dttm_created_utc  		TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by        		VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc 		TIMESTAMPTZ 	NULL
    ,modified_by       		VARCHAR(75) 	NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_status
(
     meet_status_id   	INT2    	PRIMARY KEY
    ,name             	VARCHAR(50) NOT NULL DEFAULT ''
    ,dttm_created_utc  	TIMESTAMPTZ NOT NULL DEFAULT now()
    ,created_by        	VARCHAR(75) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc 	TIMESTAMPTZ NULL
    ,modified_by       	VARCHAR(75) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_category
(
     meet_category_id  INT2		   PRIMARY KEY
	,name              VARCHAR(50) NOT NULL UNIQUE DEFAULT ''
    ,dttm_created_utc  TIMESTAMPTZ NOT NULL DEFAULT now()
    ,created_by        VARCHAR(75) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ NULL
    ,modified_by       VARCHAR(75) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_sub_category
(
     sub_category_id   INT2    	   NOT NULL
    ,meet_category_id  INT2    	   NOT NULL
    ,name              VARCHAR(50) NOT NULL DEFAULT ''
    ,created_by        VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ NULL
    ,modified_by       VARCHAR(50) NOT NULL DEFAULT ''
    
    ,PRIMARY KEY (sub_category_id, meet_category_id)
);

CREATE TABLE rangley.td_notification_type
(
     notification_type_id 	INT2	    	PRIMARY KEY
    ,name                 	VARCHAR(50) 	NOT NULL DEFAULT ''
    ,dttm_created_utc     	TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by           	VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc    	TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,modified_by          	VARCHAR(75) 	NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_icon
(
     meet_icon_id      INT2		    PRIMARY KEY
    ,name              VARCHAR(50)  NOT NULL DEFAULT ''
    ,file_type         VARCHAR(16)  NOT NULL DEFAULT ''
    ,dttm_created_utc  TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by        VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ 	NULL
    ,modified_by       VARCHAR(75) 	NOT NULL DEFAULT ''
);

-- ===== NORMAL TABLES =====

CREATE TABLE rangley.tb_meet_participants
(
     participant_id        	INT8      	 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    ,meet_id               	INT8      	 NOT NULL
    ,user_id               	INT8      	 NOT NULL
    ,participant_status_id 	INT2	     NOT NULL
    ,dttm_joined_utc       	TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,dttm_left_utc         	TIMESTAMPTZ  NULL
    ,dttm_created_utc      	TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,dttm_modified_utc     	TIMESTAMPTZ  NULL
    
    ,UNIQUE (meet_id, user_id)
);

-- participants of a meet by status
CREATE INDEX idx_part_meet_status
  ON rangley.tb_meet_participants (meet_id, participant_status_id);

-- all meets for a user (optionally by status), newest join first
CREATE INDEX idx_part_user
  ON rangley.tb_meet_participants (user_id);

CREATE INDEX idx_part_user_status_joined_desc
  ON rangley.tb_meet_participants (user_id, participant_status_id, dttm_joined_utc DESC);


CREATE TABLE rangley.tb_meets
(
     meet_id          		INT8      	 NOT NULL
    ,change_stamp     		INT8      	 NOT NULL DEFAULT 0
    ,meet_coordinate_id  	INT8      	 NOT NULL DEFAULT 0
    ,meet_status_id         INT2	     NOT NULL DEFAULT 0
    ,name             		VARCHAR(50)  NOT NULL DEFAULT ''
    ,description      		VARCHAR(50)  NOT NULL DEFAULT ''
    ,change_reason    		VARCHAR(50)  NOT NULL DEFAULT ''
    ,meet_category_id 		INT2	     NOT NULL DEFAULT 0
    ,max_capacity     		INT4	     NOT NULL DEFAULT 2
    ,dttm_start_utc   		TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,dttm_end_utc    		TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,uuid                   UUID        NOT NULL DEFAULT gen_random_uuid()

    
    ,PRIMARY KEY (meet_id, change_stamp)
);

CREATE INDEX idx_meets_category_status_start
  ON rangley.tb_meets (meet_category_id, meet_status_id, dttm_start_utc DESC);

CREATE INDEX idx_meets_category_coord
  ON rangley.tb_meets (meet_category_id, meet_coordinate_id);

CREATE INDEX IF NOT EXISTS idx_tb_meets_meetid_changestamp_desc
  ON rangley.tb_meets (meet_id, change_stamp DESC);


CREATE TABLE rangley.tb_meet_coordinates
(
     meet_coordinate_id INT8   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,latitude           FLOAT8 NOT NULL DEFAULT 0.0
    ,longitude          FLOAT8 NOT NULL DEFAULT 0.0
    ,region_latitude    FLOAT8 NOT NULL DEFAULT 0.0
    ,region_longitude   FLOAT8 NOT NULL DEFAULT 0.0
    ,region_radius      FLOAT8 NOT NULL DEFAULT 0.0
  
  	,CONSTRAINT chk_lat      CHECK (latitude BETWEEN -90  AND 90)
  	,CONSTRAINT chk_lon      CHECK (longitude BETWEEN -180 AND 180)
  	,CONSTRAINT chk_r_lat    CHECK (region_latitude BETWEEN -90  AND 90)
  	,CONSTRAINT chk_r_lon    CHECK (region_longitude BETWEEN -180 AND 180)
  	,CONSTRAINT chk_r_radius CHECK (region_radius > 0)
);

CREATE INDEX idx_meetcoord_lat_long
  ON rangley.tb_meet_coordinates (latitude, longitude);

CREATE TABLE rangley.tb_change_stamps
(
     change_stamp        INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,meet_id             INT8      		NOT NULL
    ,dttm_modified_utc   TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,modified_by_user_id INT8	     	NOT NULL DEFAULT 0
    
    ,UNIQUE(meet_id, change_stamp)
);

CREATE INDEX idx_mcs_meetid_changestamp
  ON rangley.tb_change_stamps (meet_id, change_stamp);

CREATE INDEX idx_mcs_meetid_modified_desc
  ON rangley.tb_change_stamps (meet_id, dttm_modified_utc DESC);



CREATE TABLE rangley.tb_meet_ids
(
     meet_id            INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,created_by_user_id INT8      		NOT NULL DEFAULT 0
    ,dttm_created_utc   TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,uuid               UUID            NOT NULL DEFAULT gen_random_uuid()
);


CREATE INDEX idx_meetids_createdby
  ON rangley.tb_meet_ids (created_by_user_id);


CREATE TABLE rangley.tb_users
(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

    -- External auth binding (stable for a given Cognito identity)
   ,cognito_sub          TEXT        NOT NULL UNIQUE

    -- Mutable handle but must be unique at any time; app treats it case-insensitive
   ,username             VARCHAR(50) NOT NULL UNIQUE
   ,display_name         VARCHAR(50) NOT NULL
   ,first_name           VARCHAR(50) NOT NULL DEFAULT ''
   ,last_name            VARCHAR(50) NOT NULL DEFAULT ''

    -- E.164 International format (+ then 8–15 digits). Max 16 chars with leading '+'
   ,cellphone            VARCHAR(16)
   ,email                VARCHAR(254)
   ,dob                  DATE        NOT NULL
   ,dttm_created_utc     TIMESTAMPTZ NOT NULL DEFAULT now()
   ,dttm_modified_utc    TIMESTAMPTZ
   ,uuid                 UUID        NOT NULL DEFAULT gen_random_uuid()

   -- At least one contact method must be present
  ,CONSTRAINT users_contact_one
       CHECK (email IS NOT NULL OR cellphone IS NOT NULL)

   -- Basic format/sanity guards (DB backstop)
  ,CONSTRAINT chk_users_email_fmt
       CHECK (email IS NULL OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')

  ,CONSTRAINT chk_users_cellphone_e164
       CHECK (cellphone IS NULL OR cellphone ~ '^\+[0-9]{8,15}$')

  ,CONSTRAINT chk_users_dob_reasonable
       CHECK (dob <= CURRENT_DATE AND dob >= DATE '1900-01-01')
);

-- Case-insensitive uniqueness for username (matches proc lower(...))
-- (Keeps column UNIQUE too; this prevents duplicates that differ only by case.)
CREATE UNIQUE INDEX ux_users_username_ci
  ON rangley.tb_users (lower(username));

-- Uniqueness for nullable fields (allow many NULLs, unique when present)
CREATE UNIQUE INDEX ux_users_email_ci
  ON rangley.tb_users (lower(email))
  WHERE email IS NOT NULL;

CREATE UNIQUE INDEX ux_users_cellphone
  ON rangley.tb_users (cellphone)
  WHERE cellphone IS NOT NULL;

CREATE TABLE rangley.tb_notifications
(
     notification_id      	INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY key
    ,notification_type_id 	INT2	     	NOT NULL
    ,meet_id              	INT8      		NULL
    ,created_by_user_id     INT8      		NOT null
    ,payload_json           JSONB      		NULL
    ,dttm_created_utc     	TIMESTAMPTZ  	NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notif_meet
  ON rangley.tb_notifications (meet_id);

-- CONSIDER THE JSON BLOB THING FOR NOTIFICATIONS COULD BE USEFUL???
CREATE TABLE rangley.tb_user_inboxes
(
	 user_id   			  INT8          NOT NULL
    ,notification_id 	  INT8      	NOT NULL
    ,dttm_received_utc    TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,dttm_opened_utc      TIMESTAMPTZ  	NULL
    
    ,primary key (user_id, notification_id)
);
-- fast inbox listing
CREATE INDEX IF NOT EXISTS ix_inbox_user_received_desc
  ON rangley.tb_user_inboxes (user_id, dttm_received_utc DESC);

-- (Optional) backref lookups
CREATE INDEX IF NOT EXISTS ix_inbox_notification
  ON rangley.tb_user_inboxes (notification_id);


