DROP TABLE IF EXISTS rangley.te_version_features;

DROP TABLE IF EXISTS rangley.td_meet_status;
DROP TABLE IF EXISTS rangley.td_features;
DROP TABLE IF EXISTS rangley.td_meet_category;
DROP TABLE IF EXISTS rangley.td_sub_category;
DROP TABLE IF EXISTS rangley.td_meet_icon;

DROP TABLE IF EXISTS rangley.td_participant_status;
DROP TABLE IF EXISTS rangley.td_notification_type;

DROP TABLE IF EXISTS rangley.tb_meet_participants;
DROP TABLE IF EXISTS rangley.tb_user_inboxes;
DROP TABLE IF EXISTS rangley.tb_notifications;

DROP TABLE IF EXISTS rangley.tb_users;
DROP TABLE IF EXISTS rangley.tb_meet_ids;
DROP TABLE IF EXISTS rangley.tb_change_stamps;
DROP TABLE IF EXISTS rangley.tb_meet_coordinates;
DROP TABLE IF EXISTS rangley.tb_meets;
DROP TABLE IF exists rangley.tb_user_privacy_settings 


-- Enable UUIDs if not already
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===== LOOKUP / ENUM / DICTIONARY TABLES =====

CREATE TABLE rangley.te_version_features
(
     version     INT4 NOT NULL
    ,feature_id  INT4 NOT NULL
    
    ,PRIMARY KEY (version, feature_id)
);



CREATE TABLE rangley.td_features
(
     feature_id  INT4		  PRIMARY KEY
    ,name        VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_participant_status
(
     participant_status_id  INT2	     	PRIMARY KEY
    ,name                   VARCHAR(50)  	NOT NULL UNIQUE DEFAULT ''
    ,dttm_created_utc  		TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by        		VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc 		TIMESTAMPTZ 	NULL
    ,modified_by       		VARCHAR(75) 	NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_icon
(
     meet_icon_id      INT2		    PRIMARY KEY
    ,name              VARCHAR(50)  NOT NULL DEFAULT ''
    ,file_type         VARCHAR(16)  NOT NULL DEFAULT ''
    ,dttm_created_utc  TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by        VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ 	NULL
    ,modified_by       VARCHAR(75) 	NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_status
(
     meet_status_id   	INT2    	PRIMARY KEY
    ,name             	VARCHAR(50) NOT NULL DEFAULT ''
    ,dttm_created_utc  	TIMESTAMPTZ NOT NULL DEFAULT now()
    ,created_by        	VARCHAR(75) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc 	TIMESTAMPTZ NULL
    ,modified_by       	VARCHAR(75) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_meet_category
(
     meet_category_id  INT2		   PRIMARY KEY
	,name              VARCHAR(50) NOT NULL UNIQUE DEFAULT ''
    ,dttm_created_utc  TIMESTAMPTZ NOT NULL DEFAULT now()
    ,created_by        VARCHAR(75) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ NULL
    ,modified_by       VARCHAR(75) NOT NULL DEFAULT ''
);

CREATE TABLE rangley.td_sub_category
(
     sub_category_id   INT2    	   NOT NULL
    ,meet_category_id  INT2    	   NOT NULL
    ,name              VARCHAR(50) NOT NULL DEFAULT ''
    ,created_by        VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc TIMESTAMPTZ NULL
    ,modified_by       VARCHAR(50) NOT NULL DEFAULT ''
    
    ,PRIMARY KEY (sub_category_id, meet_category_id)
);

CREATE TABLE rangley.td_notification_type
(
     notification_type_id 	INT2	    	PRIMARY KEY
    ,name                 	VARCHAR(50) 	NOT NULL DEFAULT ''
    ,dttm_created_utc     	TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,created_by           	VARCHAR(75) 	NOT NULL DEFAULT CURRENT_USER
    ,dttm_modified_utc    	TIMESTAMPTZ 	NOT NULL DEFAULT now()
    ,modified_by          	VARCHAR(75) 	NOT NULL DEFAULT ''
);

-- ===== NORMAL TABLES =====

-- ===== NEED TO ADD =======================
-- Need to add partitioning feature
-- partitioned notificaiton tabls by month
-- ===== BEFORE V2 =========================

CREATE TABLE rangley.tb_notifications
(
     notification_id      	INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY key
    ,notification_type_id 	INT2	     	NOT NULL
    ,meet_id              	INT8      		NULL
    ,created_by_user_id     INT8      		NOT null
    ,payload_json           JSONB      		NULL
    ,dttm_created_utc     	TIMESTAMPTZ  	NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notif_meet
  ON rangley.tb_notifications (meet_id);

CREATE TABLE rangley.tb_meet_participants
(
     participant_id        	INT8      	 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    ,meet_id               	INT8      	 NOT NULL
    ,user_id               	INT8      	 NOT NULL
    ,participant_status_id 	INT2	     NOT NULL
    -- Replace dttm_joined_utc with:
	,dttm_invited_utc       TIMESTAMPTZ  NOT NULL DEFAULT now()
	,dttm_accepted_utc 		TIMESTAMPTZ  NULL  -- Only populated when they accept
    ,dttm_left_utc         	TIMESTAMPTZ  NULL
    ,dttm_created_utc      	TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,dttm_modified_utc     	TIMESTAMPTZ  NULL
    
    ,UNIQUE (meet_id, user_id)
    
    -- Ensure accepted comes after invited
	,CONSTRAINT chk_accepted_after_invited 
		CHECK (dttm_accepted_utc IS NULL OR dttm_accepted_utc >= dttm_invited_utc)
);

-- participants of a meet by status
CREATE INDEX idx_part_meet_status
  ON rangley.tb_meet_participants (meet_id, participant_status_id);

-- all meets for a user (optionally by status), newest join first
CREATE INDEX idx_part_user
  ON rangley.tb_meet_participants (user_id);

CREATE INDEX idx_part_user_status 
ON rangley.tb_meet_participants (user_id, participant_status_id);

CREATE INDEX idx_part_invited_date
ON rangley.tb_meet_participants (dttm_invited_utc DESC);


CREATE TABLE rangley.tb_meets
(
     meet_id          		INT8      	 NOT NULL
    ,change_stamp     		INT8      	 NOT NULL DEFAULT 0
    ,meet_coordinate_id  	INT8      	 NOT NULL DEFAULT 0
    ,meet_status_id         INT2	     NOT NULL DEFAULT 0
    ,name             		VARCHAR(50)  NOT NULL DEFAULT ''
    ,description      		VARCHAR(50)  NOT NULL DEFAULT ''
    ,change_reason    		VARCHAR(50)  NOT NULL DEFAULT ''
    ,meet_category_id 		INT2	     NOT NULL DEFAULT 0
    ,max_capacity     		INT4	     NOT NULL DEFAULT 2
    ,dttm_start_utc   		TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,dttm_end_utc    		TIMESTAMPTZ  NOT NULL DEFAULT now()
    ,uuid                   UUID        NOT NULL DEFAULT gen_random_uuid()

    
    ,PRIMARY KEY (meet_id, change_stamp)
    
    -- In tb_meets
    ,CONSTRAINT chk_end_after_start 
		CHECK (dttm_end_utc > dttm_start_utc)
);

CREATE INDEX idx_meets_category_status_start
  ON rangley.tb_meets (meet_category_id, meet_status_id, dttm_start_utc DESC);

CREATE INDEX idx_meets_category_coord
  ON rangley.tb_meets (meet_category_id, meet_coordinate_id);

CREATE INDEX IF NOT EXISTS idx_tb_meets_meetid_changestamp_desc
  ON rangley.tb_meets (meet_id, change_stamp DESC);


CREATE TABLE rangley.tb_meet_coordinates
(
     meet_coordinate_id INT8   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,latitude           FLOAT8 NOT NULL DEFAULT 0.0
    ,longitude          FLOAT8 NOT NULL DEFAULT 0.0
    ,region_latitude    FLOAT8 NOT NULL DEFAULT 0.0
    ,region_longitude   FLOAT8 NOT NULL DEFAULT 0.0
    ,region_radius      FLOAT8 NOT NULL DEFAULT 0.0
  
  	,CONSTRAINT chk_lat      CHECK (latitude BETWEEN -90  AND 90)
  	,CONSTRAINT chk_lon      CHECK (longitude BETWEEN -180 AND 180)
  	,CONSTRAINT chk_r_lat    CHECK (region_latitude BETWEEN -90  AND 90)
  	,CONSTRAINT chk_r_lon    CHECK (region_longitude BETWEEN -180 AND 180)
  	,CONSTRAINT chk_r_radius CHECK (region_radius > 0)
);

CREATE INDEX idx_meetcoord_lat_long
  ON rangley.tb_meet_coordinates (latitude, longitude);

CREATE TABLE rangley.tb_change_stamps
(
     change_stamp        INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,meet_id             INT8      		NOT NULL
    ,dttm_modified_utc   TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,modified_by_user_id INT8	     	NOT NULL DEFAULT 0
    
    ,UNIQUE(meet_id, change_stamp)
);

CREATE INDEX idx_mcs_meetid_changestamp
  ON rangley.tb_change_stamps (meet_id, change_stamp);

CREATE INDEX idx_mcs_meetid_modified_desc
  ON rangley.tb_change_stamps (meet_id, dttm_modified_utc DESC);



CREATE TABLE rangley.tb_meet_ids
(
     meet_id            INT8      		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- how make identity be 1?
    ,created_by_user_id INT8      		NOT NULL DEFAULT 0
    ,dttm_created_utc   TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,uuid               UUID            NOT NULL DEFAULT gen_random_uuid()
);


CREATE INDEX idx_meetids_createdby
  ON rangley.tb_meet_ids (created_by_user_id);


CREATE TABLE rangley.tb_users
(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

    -- External auth binding (stable for a given Cognito identity)
   ,cognito_sub          TEXT        NOT NULL UNIQUE

    -- Mutable handle but must be unique at any time; app treats it case-insensitive
   ,username             VARCHAR(50) NOT NULL UNIQUE
   ,display_name         VARCHAR(50) NOT NULL
   ,first_name           VARCHAR(50) NOT NULL DEFAULT ''
   ,last_name            VARCHAR(50) NOT NULL DEFAULT ''

    -- E.164 International format (+ then 8–15 digits). Max 16 chars with leading '+'
   ,cellphone            VARCHAR(16)
   ,email                VARCHAR(254)
   ,dob                  DATE        NOT NULL
   ,dttm_created_utc     TIMESTAMPTZ NOT NULL DEFAULT now()
   ,dttm_modified_utc    TIMESTAMPTZ
   ,uuid                 UUID        NOT NULL DEFAULT gen_random_uuid()

   -- At least one contact method must be present
  ,CONSTRAINT users_contact_one
       CHECK (email IS NOT NULL OR cellphone IS NOT NULL)

   -- Basic format/sanity guards (DB backstop)
  ,CONSTRAINT chk_users_email_fmt
       CHECK (email IS NULL OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')

  ,CONSTRAINT chk_users_cellphone_e164
       CHECK (cellphone IS NULL OR cellphone ~ '^\+[0-9]{8,15}$')

  ,CONSTRAINT chk_users_dob_reasonable
       CHECK (dob <= CURRENT_DATE AND dob >= DATE '1900-01-01')
);

-- Case-insensitive uniqueness for username (matches proc lower(...))
-- (Keeps column UNIQUE too; this prevents duplicates that differ only by case.)
CREATE UNIQUE INDEX ux_users_username_ci
  ON rangley.tb_users (lower(username));

-- Uniqueness for nullable fields (allow many NULLs, unique when present)
CREATE UNIQUE INDEX ux_users_email_ci
  ON rangley.tb_users (lower(email))
  WHERE email IS NOT NULL;

CREATE UNIQUE INDEX ux_users_cellphone
  ON rangley.tb_users (cellphone)
  WHERE cellphone IS NOT NULL;


CREATE TABLE IF NOT EXISTS rangley.tb_user_privacy_settings 
(
     user_id 					INT8 		PRIMARY KEY 
    ,discoverable_by_username 	BOOLEAN 	DEFAULT TRUE
    ,discoverable_by_phone 		BOOLEAN 	DEFAULT FALSE
    ,discoverable_by_email 		BOOLEAN 	DEFAULT FALSE
    ,show_full_name 			BOOLEAN 	DEFAULT FALSE
    ,allow_invites_from_anyone 	BOOLEAN 	DEFAULT TRUE
    ,dttm_created_utc			TIMESTAMPTZ DEFAULT NOW()
    ,dttm_modified_utc 			TIMESTAMPTZ
);


CREATE TABLE rangley.tb_user_inboxes
(
	 user_id   			  INT8          NOT NULL
    ,notification_id 	  INT8      	NOT NULL
    ,dttm_received_utc    TIMESTAMPTZ  	NOT NULL DEFAULT now()
    ,dttm_opened_utc      TIMESTAMPTZ  	NULL
    
    ,primary key (user_id, notification_id)
);
-- fast inbox listing
CREATE INDEX IF NOT EXISTS ix_inbox_user_received_desc
  ON rangley.tb_user_inboxes (user_id, dttm_received_utc DESC);

-- (Optional) backref lookups
CREATE INDEX IF NOT EXISTS ix_inbox_notification
  ON rangley.tb_user_inboxes (notification_id);



-- Future enhancement when you add friends TODO: IMPLEMENT IN VERSION 2 OF APPLICATION
--CREATE TABLE rangley.tb_user_connections (
--    user_id 				BIGINT NOT NULL,
--    connected_user_id 		BIGINT NOT NULL,
--    connection_type 		VARCHAR(20), -- 'friend', 'follower', etc.
--    dttm_created_utc 		TIMESTAMPTZ DEFAULT NOW(),
--    PRIMARY KEY (user_id, connected_user_id)
--);




-- #################################################
-- ########	   END TABLES BEGIN TRIGGERS	########
-- #################################################

-- Triggers for users privacy settings

-- 1) Seed defaults when a user is created (no FK used)
CREATE OR REPLACE FUNCTION rangley.trg_seed_privacy_defaults()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO rangley.tb_user_privacy_settings (user_id)
  VALUES (NEW.user_id)
  ON CONFLICT (user_id) DO NOTHING;  -- idempotent
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS seed_privacy_defaults ON rangley.tb_users;
CREATE TRIGGER seed_privacy_defaults
AFTER INSERT ON rangley.tb_users
FOR EACH ROW
EXECUTE FUNCTION rangley.trg_seed_privacy_defaults();

-- 2) Touch modified timestamp on privacy updates
CREATE OR REPLACE FUNCTION rangley.trg_privacy_touch_modified()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.dttm_modified_utc := NOW();
  RETURN NEW;
END $$;





DROP TRIGGER IF EXISTS bu_privacy_touch_modified ON rangley.tb_user_privacy_settings;
CREATE TRIGGER bu_privacy_touch_modified
BEFORE UPDATE ON rangley.tb_user_privacy_settings
FOR EACH ROW
EXECUTE FUNCTION rangley.trg_privacy_touch_modified();

-- 3) (Optional) emulate cascade on user delete, still FK-free
CREATE OR REPLACE FUNCTION rangley.trg_delete_privacy_on_user_delete()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM rangley.tb_user_privacy_settings
  WHERE user_id = OLD.user_id;
  RETURN OLD;
END $$;

DROP TRIGGER IF EXISTS ad_delete_privacy_on_user_delete ON rangley.tb_users;
CREATE TRIGGER ad_delete_privacy_on_user_delete
AFTER DELETE ON rangley.tb_users
FOR EACH ROW
EXECUTE FUNCTION rangley.trg_delete_privacy_on_user_delete();


-- Insert if users already existed
INSERT INTO rangley.tb_user_privacy_settings (user_id)
SELECT u.user_id
FROM rangley.tb_users u
LEFT JOIN rangley.tb_user_privacy_settings ps USING (user_id)
WHERE ps.user_id IS NULL
ON CONFLICT (user_id) DO NOTHING;


-- Expect 0
SELECT COUNT(*) AS users_missing_privacy
FROM rangley.tb_users u
LEFT JOIN rangley.tb_user_privacy_settings ps USING (user_id)
WHERE ps.user_id IS NULL;

-- Spot-check
SELECT u.user_id, u.username, ps.discoverable_by_username, ps.discoverable_by_email, ps.discoverable_by_phone
FROM rangley.tb_users u
JOIN rangley.tb_user_privacy_settings ps USING (user_id)
ORDER BY u.user_id
LIMIT 20;
